/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 129
#define YY_END_OF_BUFFER 130
static yyconst short int yy_accept[374] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  130,  129,  126,  128,
      127,  126,    7,  128,   15,   26,  128,    4,    5,   11,
       16,   37,   17,   36,   13,  124,   39,    1,   20,    6,
       21,   38,  125,   34,   14,   35,   28,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,    2,   27,    3,
       10,  118,  119,  118,    0,   25,    0,  120,   44,   29,
       45,    0,    0,   12,   42,    8,   40,    9,   41,   32,
      116,    0,   43,    0,  124,   33,   18,   22,   24,   23,

       19,  125,   47,   31,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,   82,  125,   85,  125,  125,  125,  125,  125,   94,
       95,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  109,  125,  125,  125,  125,   46,   30,  117,
      122,  121,  121,    0,  115,  122,  123,   48,   49,   50,
      125,   53,   54,  125,  125,  125,  125,  125,  125,   62,
      125,  125,  125,  125,  125,  125,  125,  125,   79,  125,
      125,  125,  125,  125,  125,  125,   90,  125,   92,   93,
      125,  125,  125,  125,  125,  125,  102,  125,  125,  105,

      125,  125,  125,  125,  125,  125,  113,  125,    0,  125,
      125,  125,   56,  125,  125,   60,   61,  125,  125,  125,
      125,  125,   73,   74,   75,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,   89,  125,   96,   97,  125,
      125,  100,  125,  125,  104,  106,  107,  125,  110,  125,
      125,  125,    0,  123,  125,   52,  125,  125,   58,  125,
      125,  125,  125,   69,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  108,  111,  112,  125,  125,  125,  125,  125,   63,
       64,   65,   66,   67,  125,  125,  125,  125,   77,   78,

      125,  125,  125,   84,   86,  125,  125,  125,   98,   99,
      125,  125,  125,   51,  125,  125,  125,  125,  125,   71,
      125,   80,  125,  125,   87,   88,  125,  125,  125,  125,
      125,  125,  125,  125,   70,  125,  125,   81,   83,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,   91,
      125,  125,  125,  125,  125,   59,  125,   72,   76,  125,
      125,  125,  125,   57,   68,  101,  103,  114,  125,  125,
      125,   55,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,   26,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   24,   39,   40,   41,   42,
       43,   44,   24,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[380] =
    {   0,
      448,  447,    0,    0,   55,   56,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  439,  452,  452,  452,
      452,  452,   64,  433,  416,   53,  410,  452,  452,   51,
       52,  452,   67,  452,   79,   46,  414,  452,   77,  413,
       72,  412,    0,  452,  452,  452,   75,   66,   57,   74,
      389,   71,  388,  396,   83,  383,  380,   80,  382,   31,
      392,   93,  373,   95,  387,  380,  388,  452,   99,  452,
      400,  452,  452,  404,  151,    0,  414,  413,    0,    0,
        0,  409,  408,    0,    0,    0,    0,    0,    0,    0,
        0,  206,    0,  398,   90,    0,  393,    0,    0,    0,

      392,    0,    0,    0,  379,   94,   96,   96,  377,  363,
      363,  364,   94,  357,  374,  359,  357,  100,  358,  360,
      367,    0,  356,  112,  362,  358,  356,  360,  348,    0,
        0,  349,  134,  355,  352,  351,  354,  355,  357,  343,
      348,  338,    0,  350,  111,  338,  337,    0,    0,  452,
        0,  452,  373,  377,  452,  261,  134,    0,    0,  334,
      342,    0,    0,  339,  331,  332,  344,  339,  325,  342,
      329,  136,  327,  331,  333,  321,  322,  330,    0,  329,
      320,  110,  323,  326,  325,  313,    0,  323,    0,    0,
      322,  315,  320,  305,  303,  316,    0,  308,  308,    0,

      314,  298,  308,  304,  299,  303,    0,  299,  163,  307,
      298,  307,    0,  306,  298,    0,    0,  148,  288,  288,
      296,  295,    0,    0,    0,  274,  271,  270,  269,  266,
      274,  266,  268,  273,  263,    0,  261,    0,    0,  276,
      260,    0,  266,  274,    0,    0,    0,  262,    0,  267,
      266,  270,  281,  280,  250,    0,  252,  256,  249,  142,
      152,  258,  244,    0,  248,  243,  243,  252,  243,  242,
      240,  244,  227,  237,  236,  223,  222,  215,  218,  217,
      224,    0,    0,    0,  223,  210,  214,  224,  210,    0,
        0,    0,    0,    0,  222,  203,  203,  206,    0,    0,

      216,  200,  208,    0,    0,  200,  210,  213,    0,    0,
      193,  190,  189,    0,  198,  191,  199,  189,  201,  204,
      194,    0,  179,  183,    0,    0,  193,  189,  174,  172,
      168,  177,  172,  173,    0,  160,  163,    0,    0,  170,
      158,  168,  167,  153,  149,  150,  147,  152,  147,    0,
      147,  150,  149,  157,  141,    0,  136,    0,    0,  132,
      127,  123,  101,    0,    0,    0,    0,    0,  108,   34,
       43,    0,  452,  318,  321,  324,  327,   62,  330
    } ;

static yyconst short int yy_def[380] =
    {   0,
      374,  374,  373,    3,  375,  375,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  373,  373,  373,  373,
      373,  373,  373,  376,   23,   23,  377,  373,  373,   23,
       23,  373,   23,  373,   23,  373,   23,  373,   23,   23,
       23,   23,  378,  373,  373,  373,   23,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  373,   23,  373,
       23,  373,  373,  373,  373,   75,  376,  376,   75,   75,
       75,  373,  377,   75,   75,   75,   75,   75,   75,   75,
       75,  379,   75,  373,  373,   75,   75,   75,   75,   75,

       75,  378,   75,   75,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,   75,   75,  373,
       75,  373,  373,  379,  373,  379,  373,   75,   75,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  373,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  373,  373,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,    0,  373,  373,  373,  373,  373,  373
    } ;

static yyconst short int yy_nxt[510] =
    {   0,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   20,   48,
       49,   50,   51,   52,   53,   54,   43,   55,   43,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   43,   65,
       66,   43,   67,   68,   69,   70,   71,   73,   73,   80,
       94,   84,   95,   86,  102,   74,   74,   75,  131,   75,
       75,   85,   87,   81,   75,   75,  372,   75,  132,   75,
       88,   75,  371,   75,   76,   75,   75,   89,   90,   91,
       96,   75,  100,  101,   92,  103,   97,   98,  105,   93,

      115,  109,  104,  111,   94,  106,   95,  107,  110,  127,
      116,  108,  117,  128,  112,  121,  113,  122,   75,  148,
       75,  118,  129,  123,  124,  134,  135,  141,  163,  136,
      137,  161,  165,  162,  171,  172,  142,  138,  143,  144,
      139,  166,  164,  177,  205,  370,  178,  369,  206,  231,
      157,  183,  232,  149,  151,  368,  151,  151,  184,  367,
      185,  151,  151,  192,  151,  366,  151,  209,  151,  365,
      151,  151,  151,  151,  364,  290,  253,  193,  151,  254,
      194,  220,  221,  260,  222,  292,  363,  261,  291,  262,
      362,  361,  360,  359,  358,  357,  356,  355,  293,  354,

      353,  352,  351,  350,  349,  151,  348,  151,  155,  156,
      347,  156,  156,  346,  345,  344,  156,  156,  343,  156,
      342,  156,  341,  156,  340,  156,  156,  156,  156,  339,
      338,  337,  336,  156,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      156,  309,  156,  155,  156,  308,  156,  156,  307,  306,
      305,  156,  156,  304,  156,  303,  156,  302,  156,  301,
      156,  156,  156,  156,  300,  299,  298,  297,  156,  296,
      295,  294,  289,  288,  287,  286,  254,  254,  285,  284,

      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  156,  268,  156,   18,   18,
       18,   72,   72,   72,   77,  267,   77,   82,  266,   82,
      154,  154,  154,  265,  264,  263,  259,  258,  257,  256,
      255,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  230,  229,  228,  227,  226,  225,  224,  223,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  155,
      152,  208,  207,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  191,  190,  189,  188,  187,  186,  182,

      181,  180,  179,  176,  175,  174,  173,  170,  169,  168,
      167,  160,  159,  158,  157,  153,  152,   78,   78,  150,
       75,  147,  146,  145,  140,  133,  130,  126,  125,  120,
      119,  114,   75,   99,   75,   83,   79,   78,  373,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   17,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373
    } ;

static yyconst short int yy_chk[510] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    5,    6,   26,
       36,   30,   36,   31,  378,    5,    6,   23,   60,   23,
       23,   30,   31,   26,   23,   23,  371,   23,   60,   23,
       33,   23,  370,   23,   23,   23,   23,   33,   33,   35,
       39,   23,   41,   41,   35,   47,   39,   39,   48,   35,

       52,   49,   47,   50,   95,   48,   95,   48,   49,   58,
       52,   48,   52,   58,   50,   55,   50,   55,   23,   69,
       23,   52,   58,   55,   55,   62,   62,   64,  107,   62,
       62,  106,  108,  106,  113,  113,   64,   62,   64,   64,
       62,  108,  107,  118,  145,  369,  118,  363,  145,  182,
      157,  124,  182,   69,   75,  362,   75,   75,  124,  361,
      124,   75,   75,  133,   75,  360,   75,  157,   75,  357,
       75,   75,   75,   75,  355,  260,  209,  133,   75,  209,
      133,  172,  172,  218,  172,  261,  354,  218,  260,  218,
      353,  352,  351,  349,  348,  347,  346,  345,  261,  344,

      343,  342,  341,  340,  337,   75,  336,   75,   92,   92,
      334,   92,   92,  333,  332,  331,   92,   92,  330,   92,
      329,   92,  328,   92,  327,   92,   92,   92,   92,  324,
      323,  321,  320,   92,  319,  318,  317,  316,  315,  313,
      312,  311,  308,  307,  306,  303,  302,  301,  298,  297,
      296,  295,  289,  288,  287,  286,  285,  281,  280,  279,
       92,  278,   92,  156,  156,  277,  156,  156,  276,  275,
      274,  156,  156,  273,  156,  272,  156,  271,  156,  270,
      156,  156,  156,  156,  269,  268,  267,  266,  156,  265,
      263,  262,  259,  258,  257,  255,  254,  253,  252,  251,

      250,  248,  244,  243,  241,  240,  237,  235,  234,  233,
      232,  231,  230,  229,  228,  156,  227,  156,  374,  374,
      374,  375,  375,  375,  376,  226,  376,  377,  222,  377,
      379,  379,  379,  221,  220,  219,  215,  214,  212,  211,
      210,  208,  206,  205,  204,  203,  202,  201,  199,  198,
      196,  195,  194,  193,  192,  191,  188,  186,  185,  184,
      183,  181,  180,  178,  177,  176,  175,  174,  173,  171,
      170,  169,  168,  167,  166,  165,  164,  161,  160,  154,
      153,  147,  146,  144,  142,  141,  140,  139,  138,  137,
      136,  135,  134,  132,  129,  128,  127,  126,  125,  123,

      121,  120,  119,  117,  116,  115,  114,  112,  111,  110,
      109,  105,  101,   97,   94,   83,   82,   78,   77,   74,
       71,   67,   66,   65,   63,   61,   59,   57,   56,   54,
       53,   51,   42,   40,   37,   27,   25,   24,   17,   16,
       15,   14,   13,   12,   11,   10,    9,    8,    7,    2,
        1,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
#define INITIAL 0
/* This FLex file was machine-generated by the BNF converter */
#line 3 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
#include <string.h>
#include "Parser.H"
#define YY_BUFFER_LENGTH 4096
extern int yy_mylinenumber ;
char YY_PARSED_STRING[YY_BUFFER_LENGTH];
void YY_BUFFER_APPEND(char *s)
{
  strcat(YY_PARSED_STRING, s); //Do something better here!
}
void YY_BUFFER_RESET(void)
{
  for(int x = 0; x < YY_BUFFER_LENGTH; x++)
    YY_PARSED_STRING[x] = 0;
}

#define YYINITIAL 1
#define COMMENT 2
#define CHAR 3
#define CHARESC 4
#define CHAREND 5
#define STRING 6
#define ESCAPED 7

#line 623 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 26 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"


#line 777 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 374 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 452 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_0;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_1;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_2;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_3;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_4;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_5;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_6;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_7;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_8;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_9;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_10;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_15;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_16;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_17;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_18;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_19;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_20;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_21;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_22;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_23;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_24;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_25;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_26;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_27;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_28;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_29;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_30;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_31;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_34;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_35;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_36;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_37;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_38;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_39;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_40;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_41;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_42;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_43;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_44;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_45;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_46;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_47;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_48;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_49;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_50;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_51;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 80 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_52;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_53;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_54;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_55;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_56;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_57;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_58;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_59;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_60;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_61;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_62;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_63;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_64;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_65;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_66;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_67;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_68;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 97 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_69;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_70;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_71;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_72;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_73;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_74;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_75;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_76;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 105 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_77;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 106 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_78;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 107 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_79;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 108 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_80;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 109 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_81;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 110 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_82;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 111 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_83;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 112 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_84;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 113 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_85;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 114 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_86;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 115 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_87;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 116 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_88;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 117 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_89;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 118 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_90;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 119 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_91;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 120 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_92;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 121 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_93;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 122 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_94;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 123 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_95;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 124 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_96;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 125 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_97;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 126 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_98;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 127 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_99;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 128 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_100;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 129 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_101;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 130 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_102;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 131 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_103;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 132 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_104;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 133 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_105;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 134 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_106;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 135 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_107;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 136 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_108;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 137 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_109;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 138 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_110;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 139 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_111;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 140 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_112;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 141 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_113;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 143 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
++yy_mylinenumber ; 	 /* BNFC single-line comment */;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 144 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
BEGIN COMMENT;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 145 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
BEGIN YYINITIAL; return 0;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 146 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
/* BNFC multi-line comment */;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 147 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
++yy_mylinenumber ; 	 /* BNFC multi-line comment */;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 149 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _SYMB_114;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 150 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _SYMB_115;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 151 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _SYMB_116;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 152 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.double_ = atof(yytext); return _DOUBLE_;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 153 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.int_ = atoi(yytext); return _INTEGER_;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 154 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _IDENT_;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 155 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
++yy_mylinenumber ;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 156 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
/* ignore white space. */;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 157 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _ERROR_;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 158 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
ECHO;
	YY_BREAK
#line 1505 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(YYINITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 374 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 374 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 373);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 158 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"

int initialize_lexer(FILE *inp) { yyin = inp; BEGIN YYINITIAL; return 0; }
int yywrap(void) { return 1; }

