/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 224
#define YY_END_OF_BUFFER 225
static yyconst short int yy_accept[547] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  225,  224,  221,  223,
      222,  221,    7,  223,   15,   26,  223,    4,    5,   11,
       16,   37,   17,   36,   13,  219,   39,    1,   20,    6,
       21,   38,  220,   34,   14,   35,   28,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,    2,   27,    3,   10,
      213,  214,  213,    0,   25,    0,  215,   44,   29,   45,
        0,    0,   12,   42,    8,   40,    9,   41,   32,  211,
        0,   43,    0,  219,   33,   18,   22,   24,   23,   19,

      220,   47,   31,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  117,
      220,  119,  220,  220,  220,  220,  220,  220,  153,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,   46,   30,  212,  217,  216,  216,    0,  210,
      217,  218,   48,   49,  220,  220,   62,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  114,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,

        0,  220,  220,  220,  220,  220,  220,  220,  220,   77,
      220,  220,  220,  220,  220,  109,  110,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  152,  154,  220,  220,  220,  220,  220,
      220,  220,  220,  190,  220,  220,  220,  220,  220,  220,
        0,  218,  220,  220,  220,   57,  220,   61,  220,  220,
      220,   66,  220,  220,  220,   75,  220,  220,  220,   81,
      220,  220,  220,  220,  103,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  135,  220,  220,  220,  220,  142,  220,  220,  220,

      148,  149,  150,  151,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  171,  220,  220,  220,  220,  187,
      220,  197,  220,  204,  205,  220,  220,  220,  209,   50,
       51,   52,   53,   55,   56,   58,   59,  220,   63,   64,
       65,  220,  220,  220,  220,   71,  220,  220,   78,   79,
       80,  220,  220,  220,  220,  220,  220,  220,  105,  106,
      108,  220,  112,  113,  220,  220,  118,  120,  220,  220,
      220,  220,  125,  128,  129,  130,  131,  133,  134,  136,
      137,  220,  139,  140,  141,  143,  144,  145,  146,  147,
      155,  156,  158,  159,  160,  220,  220,  220,  164,  220,

      168,  169,  170,  172,  173,  220,  220,  220,  177,  180,
      181,  182,  183,  185,  186,  188,  189,  220,  220,  220,
      194,  220,  220,  220,  201,  206,  207,  208,   54,   60,
      220,   68,   69,   70,   72,   73,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  107,  220,  115,  220,  121,
      122,  123,  124,  126,  127,  132,  220,  157,  161,  162,
      163,  165,  166,  220,  174,  175,  176,  178,  179,  184,
      191,  192,  193,  195,  196,  198,  199,  200,  202,  203,
      220,  220,  220,  220,  220,  220,   85,  220,  220,  220,
       89,  220,  220,  220,   93,  220,  220,  220,   97,  220,

      220,  220,  101,  220,  104,  220,  116,  220,  220,  220,
      220,  220,   82,   83,   84,   86,   87,   88,   90,   91,
       92,   94,   95,   96,   98,   99,  100,  220,  220,  138,
      220,  220,  220,   76,  220,  111,  220,  220,   74,  102,
      167,  220,  220,  220,   67,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   18,
       17,   19,   17,   17,   17,   20,   17,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   44,   45,
       46,   47,   27,   48,   49,   50,   51,   52,   53,   54,
       55,   27,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[553] =
    {   0,
      645,  644,    0,    0,   57,   58,  643,  642,  641,  640,
      639,  638,  637,  636,  635,  634,  636,  649,  649,  649,
      649,  649,   66,  630,  610,   55,  604,  649,  649,   52,
       59,  649,   50,  649,   70,   81,  608,  649,   79,  607,
       41,  606,    0,  649,  649,  649,   64,   68,   57,   62,
      588,   76,  582,  590,   82,  577,  574,   91,  576,   81,
      586,   98,  567,   95,  581,  574,  649,   90,  649,  595,
      649,  649,  602,  146,    0,  612,  611,    0,    0,    0,
      607,  606,    0,    0,    0,    0,    0,    0,    0,    0,
      203,    0,  146,  161,    0,  589,    0,    0,    0,  588,

        0,    0,    0,  575,   98,   79,   67,  573,  559,  561,
       40,  555,  571,  556,  554,   86,  555,  557,  564,    0,
      553,   99,  559,  555,  553,  557,  545,  562,    0,  545,
      138,  551,  548,  547,  552,  554,  540,  545,  535,  547,
      107,  535,    0,    0,  649,    0,  649,  574,  578,  649,
      260,  174,    0,    0,  113,  541,    0,  547,  537,  529,
      530,  542,  537,  541,  528,  105,  539,  530,  532,  520,
      521,  529,    0,  528,  519,  517,  521,  524,  512,  527,
      521,  525,  524,  155,  518,  522,  516,  501,  499,  512,
      517,  504,  515,  509,  493,  503,  499,  494,  498,  508,

      181,  202,  502,  493,  212,  502,  504,  500,  492,    0,
      234,  482,  482,  490,  219,    0,    0,  475,  480,  480,
      479,  476,  477,  479,  475,  490,  222,  472,  225,  231,
      486,  485,  484,    0,    0,  269,  484,  468,  483,  473,
      274,  481,  277,    0,  480,  468,  478,  472,  471,  280,
      284,  303,  149,  152,  170,  177,  458,    0,  472,  471,
      470,    0,  457,  306,  461,  454,  466,  465,  464,    0,
      175,  198,  460,  446,    0,  450,  456,  455,  454,  444,
      453,  444,  447,  446,  436,  448,  435,  309,  223,  244,
      271,  250,  436,  448,  447,  446,  287,  445,  444,  443,

        0,    0,    0,    0,  438,  437,  436,  423,  427,  312,
      426,  436,  435,  434,  293,  315,  303,  304,  310,  296,
      332,    0,  335,    0,    0,  433,  432,  431,    0,    0,
        0,    0,  445,    0,    0,    0,    0,  414,    0,    0,
        0,  418,  427,  426,  425,  337,  425,  411,    0,    0,
        0,  424,  423,  422,  421,  420,  418,  399,    0,  430,
        0,  402,    0,    0,  412,  396,    0,    0,  408,  410,
      409,  408,  339,    0,    0,    0,  422,    0,    0,    0,
        0,  407,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  420,    0,    0,    0,  404,  403,  402,  341,  383,

        0,    0,    0,    0,    0,  400,  399,  398,  343,    0,
        0,    0,  412,    0,    0,    0,    0,  396,  395,  394,
      345,  393,  392,  391,  348,    0,    0,    0,    0,    0,
      380,    0,    0,    0,    0,    0,  373,  381,  352,  355,
      358,  361,  364,  371,  383,    0,  378,    0,  363,    0,
        0,    0,    0,    0,    0,    0,  382,    0,    0,    0,
        0,    0,    0,  379,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      364,  373,  364,  372,  363,  362,    0,  360,  359,  357,
        0,  356,  354,  353,    0,  351,  313,  311,    0,  305,

      302,  284,    0,  269,    0,  245,    0,  243,  227,  208,
      203,  197,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  181,  173,    0,
      169,  183,  176,    0,  165,    0,  147,  118,    0,    0,
        0,  118,  104,   73,    0,  649,  398,  401,  404,  407,
       64,  410
    } ;

static yyconst short int yy_def[553] =
    {   0,
      547,  547,  546,    3,  548,  548,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  546,  546,  546,  546,
      546,  546,  546,  549,   23,   23,  550,  546,  546,   23,
       23,  546,   23,  546,   23,  546,   23,  546,   23,   23,
       23,   23,  551,  546,  546,  546,   23,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  546,   23,  546,   23,
      546,  546,  546,  546,   74,  549,  549,   74,   74,   74,
      546,  550,   74,   74,   74,   74,   74,   74,   74,   74,
      552,   74,  546,  546,   74,   74,   74,   74,   74,   74,

      551,   74,   74,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,   74,   74,  546,   74,  546,  546,  552,  546,
      552,  546,   74,   74,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      546,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      546,  546,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,

      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,    0,  546,  546,  546,  546,
      546,  546
    } ;

static yyconst short int yy_nxt[709] =
    {   0,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   36,   36,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   20,   48,   49,   50,   51,   52,   53,   54,   43,
       55,   43,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   43,   65,   66,   43,   67,   68,   69,   70,   72,
       72,   79,   83,   87,   99,  100,  101,   73,   73,   74,
       85,   74,   74,   88,   89,   84,   74,   74,   80,   74,
       90,   74,   86,  165,  166,   91,   74,  102,   74,   75,
       74,   74,   95,   92,  103,   93,   74,   94,   94,   94,

       94,   96,   97,  104,  108,  110,  160,  111,  113,  545,
      105,  109,  106,  143,  158,  161,  107,  119,  114,  120,
      115,  129,   74,  125,   74,  121,  122,  126,  159,  116,
      138,  130,  171,  132,  133,  172,  127,  134,  156,  139,
      157,  177,  140,  198,  202,  135,  144,  199,  136,  146,
      178,  146,  146,  213,  214,  544,  146,  146,  543,  146,
      203,  146,  152,  152,  152,  152,  146,  542,  146,  146,
      146,  146,  231,  232,  233,   93,  146,   94,   94,   94,
       94,  186,  330,  541,  187,  332,  331,  188,  234,  333,
      152,  152,  152,  152,  251,  336,  337,  252,  252,  252,

      252,  540,  146,  334,  146,  150,  151,  335,  151,  151,
      201,  352,  539,  151,  151,  538,  151,  537,  151,  253,
      254,  255,  536,  151,  353,  151,  151,  151,  151,  259,
      260,  261,  535,  151,  354,  256,  277,  278,  279,  289,
      290,  291,  294,  295,  296,  262,  534,  355,  298,  299,
      300,  267,  268,  269,  533,  292,  374,  532,  297,  151,
      375,  151,  150,  151,  301,  151,  151,  270,  380,  381,
      151,  151,  271,  151,  531,  151,  272,  376,  273,  530,
      151,  377,  151,  151,  151,  151,  305,  306,  307,  529,
      151,  312,  313,  314,  317,  318,  319,  326,  327,  328,

      252,  252,  252,  252,  378,  386,  387,  315,  379,  528,
      320,  404,  405,  329,  416,  417,  151,  527,  151,  252,
      252,  252,  252,  343,  344,  345,  370,  371,  372,  396,
      397,  398,  406,  407,  408,  526,  410,  412,  525,  346,
      411,  413,  373,  414,  524,  399,  523,  415,  409,  418,
      419,  420,  422,  423,  424,  435,  436,  454,  455,  462,
      463,  468,  469,  474,  475,  421,  479,  480,  425,  484,
      485,  486,  488,  489,  490,  492,  493,  494,  496,  497,
      498,  500,  501,  502,  522,  487,  521,  520,  491,  519,
      518,  495,  517,  516,  499,  515,  514,  503,   18,   18,

       18,   71,   71,   71,   76,  513,   76,   81,  512,   81,
      149,  149,  149,  511,  510,  509,  508,  507,  506,  505,
      504,  483,  482,  481,  478,  477,  476,  473,  472,  471,
      470,  467,  466,  465,  464,  461,  460,  459,  458,  457,
      456,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  434,  433,
      432,  431,  430,  429,  428,  427,  426,  403,  402,  401,
      400,  395,  394,  393,  392,  391,  390,  389,  388,  385,
      384,  383,  382,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  351,  350,  349,

      348,  347,  342,  341,  340,  339,  338,  325,  324,  323,
      322,  321,  316,  311,  310,  309,  308,  304,  303,  302,
      293,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      276,  275,  274,  266,  265,  264,  263,  258,  257,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      150,  147,  200,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  185,  184,  183,  182,  181,  180,  179,  176,

      175,  174,  173,  170,  169,  168,  167,  164,  163,  162,
      155,  154,  153,  148,  147,   77,   77,  145,   74,  142,
      141,  137,  131,  128,  124,  123,  118,  117,  112,   74,
       98,   74,   82,   78,   77,  546,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   17,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  546,  546,  546
    } ;

static yyconst short int yy_chk[709] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    5,
        6,   26,   30,   33,   41,   41,  551,    5,    6,   23,
       31,   23,   23,   33,   33,   30,   23,   23,   26,   23,
       35,   23,   31,  111,  111,   35,   23,   47,   23,   23,
       23,   23,   39,   35,   47,   36,   23,   36,   36,   36,

       36,   39,   39,   48,   49,   50,  107,   50,   52,  544,
       48,   49,   48,   68,  106,  107,   48,   55,   52,   55,
       52,   60,   23,   58,   23,   55,   55,   58,  106,   52,
       64,   60,  116,   62,   62,  116,   58,   62,  105,   64,
      105,  122,   64,  141,  155,   62,   68,  141,   62,   74,
      122,   74,   74,  166,  166,  543,   74,   74,  542,   74,
      155,   74,   93,   93,   93,   93,   74,  538,   74,   74,
       74,   74,  184,  184,  184,   94,   74,   94,   94,   94,
       94,  131,  253,  537,  131,  254,  253,  131,  184,  254,
      152,  152,  152,  152,  201,  256,  256,  201,  201,  201,

      201,  535,   74,  255,   74,   91,   91,  255,   91,   91,
      152,  271,  533,   91,   91,  532,   91,  531,   91,  202,
      202,  202,  529,   91,  271,   91,   91,   91,   91,  205,
      205,  205,  528,   91,  272,  202,  215,  215,  215,  227,
      227,  227,  229,  229,  229,  205,  512,  272,  230,  230,
      230,  211,  211,  211,  511,  227,  289,  510,  229,   91,
      289,   91,  151,  151,  230,  151,  151,  211,  292,  292,
      151,  151,  211,  151,  509,  151,  211,  290,  211,  508,
      151,  290,  151,  151,  151,  151,  236,  236,  236,  506,
      151,  241,  241,  241,  243,  243,  243,  250,  250,  250,

      251,  251,  251,  251,  291,  297,  297,  241,  291,  504,
      243,  315,  315,  250,  320,  320,  151,  502,  151,  252,
      252,  252,  252,  264,  264,  264,  288,  288,  288,  310,
      310,  310,  316,  316,  316,  501,  317,  318,  500,  264,
      317,  318,  288,  319,  498,  310,  497,  319,  316,  321,
      321,  321,  323,  323,  323,  346,  346,  373,  373,  399,
      399,  409,  409,  421,  421,  321,  425,  425,  323,  439,
      439,  439,  440,  440,  440,  441,  441,  441,  442,  442,
      442,  443,  443,  443,  496,  439,  494,  493,  440,  492,
      490,  441,  489,  488,  442,  486,  485,  443,  547,  547,

      547,  548,  548,  548,  549,  484,  549,  550,  483,  550,
      552,  552,  552,  482,  481,  464,  457,  449,  447,  445,
      444,  438,  437,  431,  424,  423,  422,  420,  419,  418,
      413,  408,  407,  406,  400,  398,  397,  396,  392,  382,
      377,  372,  371,  370,  369,  366,  365,  362,  360,  358,
      357,  356,  355,  354,  353,  352,  348,  347,  345,  344,
      343,  342,  338,  333,  328,  327,  326,  314,  313,  312,
      311,  309,  308,  307,  306,  305,  300,  299,  298,  296,
      295,  294,  293,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  274,  273,  269,  268,  267,

      266,  265,  263,  261,  260,  259,  257,  249,  248,  247,
      246,  245,  242,  240,  239,  238,  237,  233,  232,  231,
      228,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      214,  213,  212,  209,  208,  207,  206,  204,  203,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  172,  171,  170,  169,  168,
      167,  165,  164,  163,  162,  161,  160,  159,  158,  156,
      149,  148,  142,  140,  139,  138,  137,  136,  135,  134,
      133,  132,  130,  128,  127,  126,  125,  124,  123,  121,

      119,  118,  117,  115,  114,  113,  112,  110,  109,  108,
      104,  100,   96,   82,   81,   77,   76,   73,   70,   66,
       65,   63,   61,   59,   57,   56,   54,   53,   51,   42,
       40,   37,   27,   25,   24,   17,   16,   15,   14,   13,
       12,   11,   10,    9,    8,    7,    2,    1,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  546,  546,  546
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
#define INITIAL 0
/* This FLex file was machine-generated by the BNF converter */
#line 3 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
#include <string.h>
#include "Parser.H"
#define YY_BUFFER_LENGTH 4096
extern int yy_mylinenumber ;
char YY_PARSED_STRING[YY_BUFFER_LENGTH];
void YY_BUFFER_APPEND(char *s)
{
  strcat(YY_PARSED_STRING, s); //Do something better here!
}
void YY_BUFFER_RESET(void)
{
  for(int x = 0; x < YY_BUFFER_LENGTH; x++)
    YY_PARSED_STRING[x] = 0;
}

#define YYINITIAL 1
#define COMMENT 2
#define CHAR 3
#define CHARESC 4
#define CHAREND 5
#define STRING 6
#define ESCAPED 7

#line 726 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 26 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"


#line 880 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 547 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 649 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_0;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_1;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_2;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_3;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_4;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_5;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_6;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_7;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_8;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_9;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_10;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_15;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_16;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_17;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_18;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_19;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_20;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_21;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_22;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_23;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_24;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_25;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_26;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_27;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_28;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_29;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_30;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_31;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_34;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_35;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_36;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_37;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_38;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_39;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_40;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_41;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_42;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_43;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_44;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_45;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_46;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_47;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_48;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_49;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_50;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_51;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 80 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_52;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_53;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_54;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_55;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_56;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_57;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_58;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_59;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_60;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_61;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_62;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_63;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_64;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_65;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_66;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_67;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_68;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 97 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_69;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_70;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_71;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_72;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_73;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_74;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_75;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_76;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 105 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_77;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 106 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_78;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 107 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_79;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 108 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_80;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 109 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_81;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 110 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_82;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 111 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_83;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 112 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_84;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 113 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_85;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 114 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_86;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 115 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_87;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 116 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_88;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 117 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_89;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 118 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_90;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 119 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_91;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 120 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_92;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 121 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_93;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 122 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_94;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 123 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_95;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 124 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_96;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 125 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_97;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 126 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_98;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 127 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_99;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 128 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_100;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 129 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_101;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 130 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_102;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 131 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_103;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 132 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_104;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 133 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_105;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 134 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_106;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 135 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_107;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 136 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_108;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 137 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_109;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 138 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_110;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 139 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_111;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 140 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_112;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 141 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_113;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 142 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_114;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 143 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_115;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 144 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_116;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 145 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_117;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 146 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_118;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 147 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_119;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 148 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_120;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 149 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_121;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 150 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_122;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 151 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_123;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 152 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_124;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 153 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_125;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 154 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_126;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 155 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_127;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 156 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_128;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 157 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_129;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 158 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_130;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 159 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_131;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 160 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_132;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 161 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_133;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 162 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_134;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 163 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_135;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 164 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_136;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 165 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_137;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 166 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_138;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 167 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_139;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 168 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_140;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 169 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_141;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 170 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_142;
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 171 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_143;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 172 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_144;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 173 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_145;
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 174 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_146;
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 175 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_147;
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 176 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_148;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 177 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_149;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 178 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_150;
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 179 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_151;
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 180 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_152;
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 181 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_153;
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 182 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_154;
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 183 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_155;
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 184 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_156;
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 185 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_157;
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 186 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_158;
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 187 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_159;
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 188 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_160;
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 189 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_161;
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 190 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_162;
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 191 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_163;
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 192 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_164;
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 193 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_165;
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 194 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_166;
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 195 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_167;
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 196 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_168;
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 197 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_169;
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 198 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_170;
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 199 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_171;
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 200 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_172;
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 201 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_173;
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 202 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_174;
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 203 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_175;
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 204 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_176;
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 205 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_177;
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 206 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_178;
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 207 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_179;
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 208 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_180;
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 209 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_181;
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 210 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_182;
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 211 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_183;
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 212 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_184;
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 213 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_185;
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 214 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_186;
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 215 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_187;
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 216 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_188;
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 217 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_189;
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 218 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_190;
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 219 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_191;
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 220 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_192;
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 221 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_193;
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 222 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_194;
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 223 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_195;
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 224 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_196;
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 225 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_197;
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 226 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_198;
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 227 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_199;
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 228 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_200;
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 229 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_201;
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 230 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_202;
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 231 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_203;
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 232 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_204;
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 233 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_205;
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 234 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_206;
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 235 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_207;
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 236 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _SYMB_208;
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 238 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
++yy_mylinenumber ; 	 /* BNFC single-line comment */;
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 239 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
BEGIN COMMENT;
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 240 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
BEGIN YYINITIAL; return 0;
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 241 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
/* BNFC multi-line comment */;
	YY_BREAK
case 214:
YY_RULE_SETUP
#line 242 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
++yy_mylinenumber ; 	 /* BNFC multi-line comment */;
	YY_BREAK
case 215:
YY_RULE_SETUP
#line 244 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _SYMB_209;
	YY_BREAK
case 216:
YY_RULE_SETUP
#line 245 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _SYMB_210;
	YY_BREAK
case 217:
YY_RULE_SETUP
#line 246 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _SYMB_211;
	YY_BREAK
case 218:
YY_RULE_SETUP
#line 247 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.double_ = atof(yytext); return _DOUBLE_;
	YY_BREAK
case 219:
YY_RULE_SETUP
#line 248 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.int_ = atoi(yytext); return _INTEGER_;
	YY_BREAK
case 220:
YY_RULE_SETUP
#line 249 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
yylval.string_ = strdup(yytext); return _IDENT_;
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 250 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
++yy_mylinenumber ;
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 251 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
/* ignore white space. */;
	YY_BREAK
case 223:
YY_RULE_SETUP
#line 252 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
return _ERROR_;
	YY_BREAK
case 224:
YY_RULE_SETUP
#line 253 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"
ECHO;
	YY_BREAK
#line 2083 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(YYINITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 547 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 547 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 546);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 253 "C:\\Users\\Semi\\Documents\\cp1\\cp1\\cp1\\.l"

int initialize_lexer(FILE *inp) { yyin = inp; BEGIN YYINITIAL; return 0; }
int yywrap(void) { return 1; }

